### PR TITLE
added recommendations functions in User and Organization

### PR DESCRIPTION
**Pull request by omarradwan**
boss howa ana makontesh fahem ana el mafrod a3mel eh aslun , lessa matfarragtesh 3al video elly feh el kalam da. bs shoft zar3y 3amel eh fe el subscribtions w 3amalt zayo :'D 
el mohemm lw feeh 7aga 8abeya olly beshweesh ya3ny :'D

### CODE REVIEW

**Comment by omarradwan** [comment]
sanya, how msh el mfrod el recommendation teb2a entity aslun?

**Comment by AhmadElsagheer** [comment]
Hi Omar. Yes, I think you are right. For a cleaner implementation, we will need a model for the recommendations. As a consequence, we will need to edit the recommendations table to be named "recommendations" and the model will be named "Recommendation". We will have a one-to-many relationship between the recommendation and the user and a one-to-many relationship between the organization and the recommendation. So Now we need to:
1. edit the migration for the table
2. make a model for recommendation
3. relationship functions in the three mentioned models
4. A function OrganizationControlller.createRecommendation that will return a view for the recommendation form
5. A function OrganizationController.storeRecommendation that will create a new recommendation instance and save it in the recommendations of the authenticated user and specified organization

**Comment by AhmadElsagheer** [comment]
Omar, Mostafa told me that there is a way to do it with the same table we have using the many-to-many relationship, we can discuss it tomorrow

**Comment by AhmadElsagheer** [comment]
Omar, Mostafa told me that there is a way to do it with the same table we have using the many-to-many relationship, we can discuss it tomorrow

**Comment by omarradwan** [comment]
I pulled the master to my local branch to start working. but unfortunately, I found an error in bootstrap/cache/compiled.php. It says: 

Class 'Collective\Html\HtmlServiceProvider' not found in /home/omar/E/TechHub/kheir-blogger/bootstrap/cache/compiled.php on line 7497

I can't even create a new migration because of this error. Any idea how to fix that?

**Comment by EsraaaSalah** [comment]
Ashraf nazel packages gdida 
Ekteb $composer install fel terminal 😄

**Comment by omarradwan** [comment]
foll :dancer:

**Comment by omarradwan** [comment]
Done

**Comment by omarradwan** [comment]
sa8er? :'D

**Pull request merged**
