### PR TITLE
Recommendations table

### PR DESCRIPTION
**Pull request by khlyy**

### CODE REVIEW

**Comment by omarradwan** [comment]
5elly kan 3amel sign in mn 3ndy :'D

**Comment by AhmadElsagheer** [comment]
1. make all migration contents in the same Schema::create function.
2. foreign key constraint of organization_id is not correct (what is org_id?)
3. something is wrong with workspace.xml (check changed files). If you have messed up some things, pull the master branch again, make a new migration and copy the old one's content in it

**Comment by omarradwan** [comment]
be5

**Comment by omarradwan** [comment]
ba2ollak a , 7war el file bta3 workspace.xml da 7asal feh changes bardo , bs ana ma3amaltlosh add wala commit , bs 7ases enno hy3okk el donya , w msh 3aref eh elly by5alleh ye8ayar aslun :'D

**Comment by AhmadElsagheer** [comment]
OK, don't delete it again. You can just fetch from the master this file and replace the one on your machine with it

**Pull request closed without merging**
