### PR TITLE
Moved show method to 'User' model from 'Volunteer' controller

### PR DESCRIPTION
**Pull request by IElgohary**

### CODE REVIEW

**Comment by AhmadElsagheer** [comment]
Resolve conflicts and don't add workspace.xml file

**Comment by IElgohary** [comment]
I tried everything I found to solve the conflict in .idea but I can't seem to fix it

**Comment by AhmadElsagheer** [comment]
Always compare before making a pull request. 28 files have been changed. I have removed .idea folder from the repo. Adjust your branch so that you will have only the target file changed

**Comment by IElgohary** [comment]
bs ana ma3'yartesh 3'er 3 files el 28 dol gom mnen?

**Pull request merged**
