### PR TITLE
Recommendations table 3ala nadafa

### PR DESCRIPTION
**Pull request by omarradwan**
dawart shwaya fe 7war el file bta3 workspace.xml elly by7sallo change. 7atteto fe .gitignore.
w belnesba lel error bta3 el foreign key msh sha8al m3aya 5ales w mosammem en el esm taweel

### CODE REVIEW

**Comment by omarradwan** [comment]
shakly 3akket el donia bel 11 file changed de :'D

**Comment by AhmadElsagheer** [comment]
ah nta 3akketha f3ln :D ok delete the branch on your local machine, pull from master and don't commit everything. only commit the migration file

**Comment by omarradwan** [comment]
tb enta lw 3mlt merge keda a el moshkela? 
ana masa7t el lines de bs ma7attetsh 7aga mkanha zy el marra elly fatet , fa msh haye7sal conflict a3taqed , walla a ?

**Comment by AhmadElsagheer** [comment]
you deleted _too many things_ :D check "Files changed"

**Comment by omarradwan** [comment]
ana fahem , bs da 3andy ana , ya3ny lamma te3mel merge m3 el master el 7agat de hateb2a deleted mn el master bardo?

**Pull request closed without merging**
